<definitions name="EvaluationService" targetNamespace="http://www.devshare.com/soap/evaluation"
  xmlns:tns="http://www.devshare.com/soap/evaluation"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns="http://schemas.xmlsoap.org/wsdl/">

  <message name="getEvaluationRequest">
    <part name="developerId" type="xsd:int"/>
    <part name="skillId" type="xsd:int"/>
  </message>

  <message name="getEvaluationResponse">
    <part name="status" type="xsd:string"/>
    <part name="result" type="xsd:int"/>
    <part name="skillName" type="xsd:string"/>
    <part name="levelName" type="xsd:string"/>
    <part name="date" type="xsd:date"/>
  </message>

  <portType name="EvaluationPortType">
    <operation name="getEvaluation">
      <input message="tns:getEvaluationRequest"/>
      <output message="tns:getEvaluationResponse"/>
    </operation>
  </portType>

  <binding name="EvaluationBinding" type="tns:EvaluationPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getEvaluation">
      <soap:operation soapAction="http://www.devshare.com/soap/evaluation#getEvaluation"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="EvaluationService">
    <port name="EvaluationPort" binding="tns:EvaluationBinding">
      <soap:address location="http://localhost:3000/soap"/>
    </port>
  </service>
</definitions>
