<definitions name="SimpleService" targetNamespace="http://www.devshare.com/soap/evaluation"
  xmlns:tns="http://www.devshare.com/soap/evaluation"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns="http://schemas.xmlsoap.org/wsdl/">

  <message name="simpleRequest">
    <part name="input" type="xsd:string"/>
  </message>

  <message name="simpleResponse">
    <part name="output" type="xsd:string"/>
  </message>

  <portType name="SimplePortType">
    <operation name="simpleOperation">
      <input message="tns:simpleRequest"/>
      <output message="tns:simpleResponse"/>
    </operation>
  </portType>

  <binding name="SimpleBinding" type="tns:SimplePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="simpleOperation">
      <soap:operation soapAction="http://www.devshare.com/soap/evaluation#simpleOperation"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="SimpleService">
    <port name="SimplePort" binding="tns:SimpleBinding">
      <soap:address location="http://localhost:3000/soap/evaluation"/>
    </port>
  </service>
</definitions>
